steps:
  - name: Dotnet restore
    command: nix-shell . "dotnet restore src/WebHello/WebHello.fsproj"

  - name: Dotnet publish
    command: nix-shell . "dotnet publish src/WebHello/WebHello.fsproj -o out -c Release --no-restore"
