steps:
  - name: "NuGet restore"
    command: "nix-shell . --run \"dotnet restore WebHello/WebHello.fsproj\""

  - wait

  - name: "Dotnet publish"
    command: "nix-shell . --run \"dotnet publish WebHello/WebHello.fsproj -o out -c Release --no-restore\""
