steps:
  - name: Test
    command: cat /app/src/WebHello/WebHello.fsproj
    plugins:
      docker-compose#v2.4.0:
        run: app

  - wait

  - name: Dotnet restore
    command: dotnet restore /app/src/WebHello/WebHello.fsproj
    plugins:
      docker-compose#v2.4.0:
        run: app
