steps:
  - name: Dotnet restore
    command: dotnet restore /app/src/WebHello/WebHello.fsproj
    plugins:
      docker-compose#v2.4.0:
        run: app
        workdir: /app
        volumes:
          - ./:/app
  - name: Test
    command: echo $(ls)
    plugins:
      docker-compose#v2.4.0:
        run: app
        workdir: /app
        volumes:
          - ./:/app
  - name: Test 2
    command: echo $(ls /app)
    plugins:
      docker-compose#v2.4.0:
        run: app
        workdir: /app
        volumes:
          - ./:/app
  - name: Test 3
    command: echo $(ls /app/src/WebHello)
    plugins:
      docker-compose#v2.4.0:
        run: app
        workdir: /app
        volumes:
          - ./:/app
