steps:
  - name: Test
    command: cat /app/src/WebHello/WebHello.fsproj
    plugins:
      docker#v1.2.1:
        image: microsoft/dotnet:2.0-sdk
        workdir: /app
        mounts:
          - /var/run/docker.sock:/var/run/docker.sock

  - wait

  - name: Dotnet restore
    command: dotnet restore /app/src/WebHello/WebHello.fsproj
    plugins:
      docker-compose#v2.4.0:
        run: app
